name: Docker MeshCentral 

on:
  schedule:
    - cron:  '0 0 * * FRI'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      meshcentral_version: ${{ steps.new_version_check.outputs.meshcentral_version }}
    steps:
      - name: new check version
        id: new_version_check
        run: |
          releases=$(curl -s "https://api.github.com/repos/Ylianst/MeshCentral/releases?per_page=1")
          last_week_releases=$(echo $releases | jq --arg date "$(date -d "2 months ago" +%Y-%m-%dT%H:%M:%SZ)" '.[] | select(.published_at >= $date)')
          echo "meshcentral_version=$(echo $last_week_releases | jq -r .name )" >> "$GITHUB_OUTPUT"

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      if: needs.check.outputs.meshcentral_version != ''
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin 
    - name: docker buildx multiarch
      if: needs.check.outputs.meshcentral_version != ''
      run: |
        docker buildx create --name multiarch
        docker buildx use multiarch
        docker buildx inspect --bootstrap
    -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      if: needs.check.outputs.meshcentral_version != ''
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      if: needs.check.outputs.meshcentral_version != ''
      uses: docker/setup-buildx-action@v2
      
    - name: docker build meshcentral
      if: needs.check.outputs.meshcentral_version != ''
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |
        docker buildx build . -t $DOCKER_USER/meshcentral:latest -t $DOCKER_USER/meshcentral:${{ needs.check.outputs.meshcentral_version }} --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 --push

# ,linux/ppc64le,linux/s390x,linux/386
